/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.the77TCollective.stocks.util.json;

/**
 *
 * @author BobDevelopment
 */
   


/**
 * <p>Autogenerated code in Quote.java with php script:</p>
 * <code>
 * &lt;?php<br />
 * $availableFields= array('Ask','AverageDailyVolume','Bid','AskRealtime',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'BidRealtime','BookValue','Change&PercentChange','Change','Commission',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'ChangeRealtime','AfterHoursChangeRealtime','DividendShare','LastTradeDate',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'TradeDate','EarningsShare','ErrorIndicationreturnedforsymbolchangedinvalid',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'EPSEstimateCurrentYear','EPSEstimateNextYear','EPSEstimateNextQuarter',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'DaysLow','DaysHigh','YearLow','YearHigh','HoldingsGainPercent',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'AnnualizedGain','HoldingsGain','HoldingsGainPercentRealtime',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'HoldingsGainRealtime','MoreInfo','OrderBookRealtime','MarketCapitalization',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'MarketCapRealtime','EBITDA','ChangeFromYearLow','PercentChangeFromYearLow',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'LastTradeRealtimeWithTime','ChangePercentRealtime','ChangeFromYearHigh',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'PercebtChangeFromYearHigh','LastTradeWithTime','LastTradePriceOnly',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'HighLimit','LowLimit','DaysRange','DaysRangeRealtime',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'FiftydayMovingAverage','TwoHundreddayMovingAverage',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'ChangeFromTwoHundreddayMovingAverage',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'PercentChangeFromTwoHundreddayMovingAverage',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'ChangeFromFiftydayMovingAverage','PercentChangeFromFiftydayMovingAverage',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'Name','Notes','Open','PreviousClose','PricePaid','ChangeinPercent',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'PriceSales','PriceBook','ExDividendDate','PERatio','DividendPayDate',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'PERatioRealtime','PEGRatio','PriceEPSEstimateCurrentYear',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'PriceEPSEstimateNextYear','Symbol','SharesOwned','ShortRatio',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'LastTradeTime','TickerTrend','OneyrTargetPrice','Volume','HoldingsValue',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'HoldingsValueRealtime','YearRange','DaysValueChange',<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;'DaysValueChangeRealtime','StockExchange','DividendYield');<br /><br />
 * foreach($availableFields as $value)<br />
 * {<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;echo '    /**<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&frasl;<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;protected String ' . $value . ';' . PHP_EOL;<br />
 * }<br />
 * foreach($availableFields as $value)<br />
 * {<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;echo '    /**<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* @return String ' . $value  . '<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&frasl;<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;public String get' . $value . '()<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;{<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return ' . $value . ';<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;}' . PHP_EOL;<br />
 * }<br />
 * foreach($availableFields as $value)<br />
 * {<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;echo '    /**<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* @param ' . $value . ' String<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&frasl;<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;public void set' . $value . '(String ' . $value . ')<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;{<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.' . $value . ' = ' . $value . ';<br />
 * &nbsp;&nbsp;&nbsp;&nbsp;}' . PHP_EOL;<br />
 * }<br />
 * ?&gt;<br />
 * </code>
 * @author paddy (Patrick-Emil Zörner)
 */
public class Stats
{
    /** 
     *
     */
    protected BaseStockStatContent PEGRatio;
    /**
     * 
     * 
     */
    protected BaseStockStatContent ForwardPE;
    /**
     * 
     * 
     */    
    protected BaseStockStatContent CurrentRatio;
    /**
     * 
     * 
     */
    protected BaseStockStatContent LeveredFreeCashFlow;  
    /**
     *
     */
    protected BaseStockStatContent PriceBook;
    /**
     *
     */
    protected String PERatio;
    /**
     *
     */
    protected String PERatioRealtime;
    /**
     *
     */
    protected String symbol;
    /**
     *
     */
    protected BaseStockStatContent ShortRatio;
    /**
     *
     */
    protected String DividendYield;      
    
    /**
     *
     * @return String PriceBook
     */
    public BaseStockStatContent getPriceBook()
    {
            return PriceBook;
    }
    /**
     *
     * @return String PERatio
     */
    public String getPERatio()
    {
            return PERatio;
    }
    /**
     * 
     * @return CurrentRatio
     */
    public BaseStockStatContent getCurrentRatio() {
        return CurrentRatio;
    }
    /**
     * 
     * @return LeveredFreeCashFlow 
     */
    
    public BaseStockStatContent getLeveredFreeCashFlow() {
        return LeveredFreeCashFlow;
    }
    /**
     *
     * @return String PEGRatio
     */
    public BaseStockStatContent getPEGRatio()
    {
            return PEGRatio;
    }
    /**
     * return ForwardPE
     */
     public BaseStockStatContent getForwardPE() {
        return ForwardPE;
    }
    /**
     *
     * @return String Symbol
     */
    public String getsymbol()
    {
            return symbol;
    }

    /**
     *
     * @return String ShortRatio
     */
    public BaseStockStatContent getShortRatio()
    {
            return ShortRatio;
    }
    
    /**
     *
     * @return String DividendYield
     */
    public String getDividendYield()
    {
            return DividendYield;
    }
    
   
    /**
     *
     * @param PriceBook String
     */
    public void setPriceBook(BaseStockStatContent PriceBook)
    {
        this.PriceBook = PriceBook;
    }
    
    /**
     *
     * @param PERatioRealtime String
     */
    public void setPERatioRealtime(String PERatioRealtime)
    {
        this.PERatioRealtime = PERatioRealtime;
    }
    /**
     *
     * @param PEGRatio String
     */
    public void setPEGRatio(PEGRatio PEGRatio)
    {
        this.PEGRatio = PEGRatio;
    }
    /**
     *
     * @param Symbol String
     */
    public void setsymbol(String symbol)
    {
        this.symbol = symbol;
    }
    
    /**
     *
     * @param ShortRatio String
     */
    public void setShortRatio(BaseStockStatContent ShortRatio)
    {
        this.ShortRatio = ShortRatio;
    }
    /**
     * 
     * @param currentRatio 
     */
    public void setCurrentRatio(BaseStockStatContent currentRatio){
        this.CurrentRatio = currentRatio;
    }
    /**
     * 
     * @param forwardPE 
     */
    public void setForwardPE(BaseStockStatContent forwardPE){
        this.ForwardPE = forwardPE;
    }
    /**
     * 
     * @param leveredFreeCashFlow 
     */
    public void setLeveredFreeCashFlow(BaseStockStatContent leveredFreeCashFlow){
        this.LeveredFreeCashFlow = leveredFreeCashFlow;
    }
    /**
     *
     * @param DividendYield String
     */
    public void setDividendYield(String DividendYield)
    {
        this.DividendYield = DividendYield;
    }
}
